objects/Issue__c.object
<CustomObject>
    <fields>
        <fullName>Issue_Type__c</fullName>
        <label>Issue Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bug</fullName>
                </value>
                <value>
                    <fullName>Task</fullName>
                </value>
                <value>
                    <fullName>Epic</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Summary__c</fullName>
        <label>Summary</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Issue</label>
    <nameField>
        <displayFormat>HQ-{0}</displayFormat>
        <label>Issue No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/IssueControllerClassTest.cls
@isTest
private class IssueControllerClassTest {
	@isTest
    private static void firstMethod()
    {
        List<Issue__c> issue = New List<Issue__c>();
        
        Issue__c iss1 = New Issue__c();
        iss1.Summary__c = 'Test';
        iss1.Issue_Type__c = 'Bug';
        issue.add(iss1);
        
        Issue__c iss2 = New Issue__c();
        iss2.Summary__c = 'Test2';
        iss2.Issue_Type__c = 'Task';
        issue.add(iss2);
        
        Issue__c iss3 = New Issue__c();
        iss3.Summary__c = 'Test3';
        iss3.Issue_Type__c = 'Epic';
        issue.add(iss3);
        
        test.startTest();
        Insert issue;
        test.stopTest();
    }
}