objects/Issue__c.object
<CustomObject>
    <fields>
        <fullName>Issue_Type__c</fullName>
        <label>Issue Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bug</fullName>
                </value>
                <value>
                    <fullName>Task</fullName>
                </value>
                <value>
                    <fullName>Epic</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Medium</fullName>
                    <default>true</default>
                    <label>Medium</label>
                </value>
                <value>
                    <fullName>Highest</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Lowest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Issue</label>
    <nameField>
        <displayFormat>HQ-{0}</displayFormat>
        <label>Issue No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/IssueControllerClass.cls
public class IssueControllerClass {
	public static void SetPriority(List<Issue__c> issueList)
    {
        for(Issue__c iss:issueList)
        {
            if(iss.Issue_Type__c == 'Bug')
            {
                iss.Priority__c = 'High';
            }
            else if(iss.Issue_Type__c == 'Task')
            {
                iss.Priority__c = 'Medium';
            }
            else
            {
                iss.Priority__c = 'Low';
            }
        }
    }
}