CPQ/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__PricingMethod__c</fullName>
        <description>Determines how the price for this line item is set. &quot;List&quot; = calculated by subtracting discount from list price. &quot;Cost&quot;  = calculated by adding markup to cost.</description>
        <inlineHelpText>Indicates how the price for this line item is calculated. &quot;List&quot; = subtracting discount from list price. &quot;Cost&quot; = adding markup to cost.</inlineHelpText>
        <label>Pricing Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>List</fullName>
                    <default>true</default>
                    <label>List</label>
                </value>
                <value>
                    <fullName>Cost</fullName>
                </value>
                <value>
                    <fullName>Block</fullName>
                </value>
                <value>
                    <fullName>Percent Of Total</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

CPQ/objects/SBQQ__OrderItemConsumptionRate__c.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>5</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SBQQ__LowerBound__c</fullName>
        <inlineHelpText>The lowest quantity of usage for this consumption rate.</inlineHelpText>
        <label>Lower Bound</label>
        <precision>9</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__OrderItemConsumptionSchedule__c</fullName>
        <inlineHelpText>This rate is a part of of this schedule.</inlineHelpText>
        <label>Order Product Consumption Schedule</label>
        <referenceTo>SBQQ__OrderItemConsumptionSchedule__c</referenceTo>
        <relationshipLabel>Order Product Consumption Rates</relationshipLabel>
        <relationshipName>OrderItemConsumptionRates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SBQQ__Price__c</fullName>
        <inlineHelpText>The price for usage that falls within this consumption rate&apos;s bounds.</inlineHelpText>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>7</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__PricingMethod__c</fullName>
        <label>Pricing Method</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PerUnit</fullName>
                    <label>Per Unit</label>
                </value>
                <value>
                    <fullName>FlatFee</fullName>
                    <label>Flat Fee</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__ProcessingOrder__c</fullName>
        <inlineHelpText>The order for processing the usage rate across multiple rates. Consumption Rates are evaluated beginning with the lowest processing order.</inlineHelpText>
        <label>Processing Order</label>
        <precision>9</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order Product Consumption Rate</label>
    <nameField>
        <label>Order Product Consumption Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Product Consumption Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CPQ/objects/SBQQ__OrderItemConsumptionSchedule__c.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>5</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Order Product Consumption Schedule</label>
    <nameField>
        <label>Order Product Consumption Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Product Consumption Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CPQ/classes/CreateRecord.cls
public class CreateRecord {
	public static void parentRecords()
    {
        //CREATE RECORDS
        /*List<OrderItem> quote = [SELECT ID, External_ID__c FROM OrderItem];
        
        Integer ct = 1;
        for(OrderItem sb:quote)
        {
            sb.External_ID__c = 'OR-'+ct;
            ct++;
        }
        
        UPDATE quote;*/
        
        SBQQ__OrderItemConsumptionRate__c qd = New SBQQ__OrderItemConsumptionRate__c();
        
        qd.Name = 'OPCR-FD65';
        qd.External_ID__c  = 'OCR-1';
        qd.SBQQ__OrderItemConsumptionSchedule__c = 'a1F3x00000eykj2EAA';
        qd.SBQQ__LowerBound__c = 10;
        qd.SBQQ__Price__c = 2500;
        qd.SBQQ__PricingMethod__c = 'Per Unit';
        qd.SBQQ__ProcessingOrder__c = 5;
        
        INSERT qd;
    }
}